// Generated by CoffeeScript 1.6.3
(function() {
  var CubeIcon;

  module.exports = function(opts) {
    return new CubeIcon(opts);
  };

  CubeIcon = (function() {
    function CubeIcon(opts) {
      var ch, cubeH, cubeW, cw, dz, face, faceName, faceTransforms, i, rotateX, rotateY, s, scale, showFaces, _i, _len, _ref, _ref1, _ref2, _ref3, _ref4;
      if (opts == null) {
        opts = {};
      }
      showFaces = (_ref = opts.showFaces) != null ? _ref : ['left', 'top', 'front'];
      if (opts.side != null) {
        opts.left = opts.front = opts.side;
      }
      rotateX = (_ref1 = opts.rotateX) != null ? _ref1 : -30;
      rotateY = (_ref2 = opts.rotateY) != null ? _ref2 : 45;
      scale = (_ref3 = opts.scale) != null ? _ref3 : 4;
      s = (_ref4 = opts.size) != null ? _ref4 : 16;
      this.container = document.createElement('div');
      cw = ch = 100;
      cubeW = Math.floor(ch / (1 - Math.sin(rotateX * Math.PI / 180)) - 2);
      cubeH = Math.ceil(cw / (1 + Math.cos(rotateY * Math.PI / 180)) + 1);
      console.log(cw, s, cubeW);
      console.log(ch, s, cubeH);
      this.container.setAttribute('style', "-webkit-transform: rotateX(" + rotateX + "deg) rotateY(" + rotateY + "deg) translateX(" + (cw - s * scale) + "px) translateY(" + (ch - s * scale) + "px) scale3d(" + scale + "," + scale + "," + scale + ");-webkit-transform-origin: 0 0;position: relative;-webkit-transform-style: preserve-3d;");
      dz = s / 2;
      faceTransforms = {
        front: "rotateY(   0deg ) translateZ( " + dz + "px )",
        back: "rotateX( 180deg ) translateZ( " + dz + "px )",
        right: "rotateY(  90deg ) translateZ( " + dz + "px )",
        left: "rotateY( -90deg ) translateZ( " + dz + "px )",
        top: "rotateX(  90deg ) translateZ( " + dz + "px )",
        bottom: "rotateX( -90deg ) translateZ( " + dz + "px )"
      };
      for (i = _i = 0, _len = showFaces.length; _i < _len; i = ++_i) {
        faceName = showFaces[i];
        face = document.createElement('div');
        face.setAttribute('style', "-webkit-transform-style: preserve-3d;-webkit-transform: " + faceTransforms[faceName] + ";position: absolute;border: 0.5px solid black;width: " + s + "px;height: " + s + "px;");
        face.style.backgroundImage = 'url(' + opts[faceName] + ')';
        this.container.style.webkitTransition = '-webkit-transform 1s';
        this.container.appendChild(face);
      }
    }

    return CubeIcon;

  })();

}).call(this);
